<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<!--<TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->
		<AnalysisLevel>8-all</AnalysisLevel>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
		<WarningsNotAsErrors>CA1034,CA1062,CA1724,CA2007,CA1848</WarningsNotAsErrors>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Core" />
		<PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
    <PackageReference Include="Azure.ResourceManager" />
		<PackageReference Include="Flurl" />
		<PackageReference Include="LanguageExt.Core" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Http.Resilience" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
		<PackageReference Include="Microsoft.OpenApi.Readers" />
    <PackageReference Include="NetEscapades.Configuration.Yaml" />
		<PackageReference Include="Nito.Comparers" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
		<PackageReference Include="Polly" />
		<PackageReference Include="System.Interactive.Async" />
		<PackageReference Include="System.Linq.Async" />
		<PackageReference Include="Yaml2JsonNode" />
		<PackageReference Include="YamlDotNet.System.Text.Json" />
	</ItemGroup>

</Project>
